### ISSUE TITLE
Error in `*tmp*`[[i]] : subscript out of bounds

### ISSUE THREAD

**Issue by postalguy** [debarros/tabsetPanel2#2]
I executed the example code to make sure that I did everything good but kept getting this error in both codes (yours and mine)

**Comment by ldbro0** [comment]
I can confirm the same error.

**Comment by debarros** [comment]
Sorry for the delay.  It looks like Shiny changed some stuff in the background at some point and I had to update the way that sublists of tabset$content$children get accessed.  It should work now.
